### ISSUE TITLE
reduceCube produces different values than the old spatialMean function ?

### ISSUE THREAD

**Issue by Torminator** [CAB-LAB/JuliaDatDemo#4]
Example: Variance.ipynb 
mv1 = reduceCube(mean, v1, LatAxis, skipnull=true)
     Mean variance with seasonal cycle: 0.0061406395
     Mean variance without seasonal cycle: 0.0038614897
mv1 =mapCube(spatialMean,(v1,v1.axes[2])):
     Mean variance with seasonal cycle: 0.008488666
     Mean variance without seasonal cycle: 0.006032313

**Comment by meggart** [comment]
The old spatialMean function was wrong, it did not incluude spatial weights according to grid cell size. Are you also sure that the same data cube version was used by both examples? 

However, we could still check if the values make sense, so I leave the issue open for now...

**Comment by Torminator** [comment]
Sorry, they used different data cubes.
